import Head from 'next/head'
import Image from 'next/image'
 import styles from '../../styles/Home.module.css'
import Link from "next/link"
import React,{useEffect,useState} from "react";
import { useRouter } from 'next/router';


export default function NumberTable() {
  const router = useRouter();
  let query_data=router.query;
  console.log("query_data",query_data);
  // const {
  //   query: { startNumber,endNumber },
  // } = router
  const [dataTable,SetdataTable] =useState([]);
  var obj_array=[];
  var NumberTable = query_data ? query_data.data : 0;
  var StartPoint = query_data ? query_data.NumberTable[0] : 0;
  var EndPoint = query_data ? query_data.NumberTable[1] : 0;
  // console.log("the date from the url is",query_data.data);
  // console.log("the start_point from the url is",query_data.start_number);
  // console.log("the end_point from the url is",query_data.end_number);
  var rendertable= "";
  useEffect(()=>{
    for(let i = StartPoint ; i <= EndPoint ; i++) {
      const result = i * NumberTable;
      var array_obj={number:NumberTable,multiplier:i,Result:result};
      obj_array.push(array_obj)
    } 
    console.log("obj_array",obj_array);
    SetdataTable(obj_array)
    console.log("SetdataTable",obj_array);
  },NumberTable);
   
  return (
    <div className={styles.container}>
      <Head>
        <title>Table of {NumberTable}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div><h1>Table of {NumberTable}</h1></div>
          <button className="btn btn-default" type="button" onClick={() => router.back()}>
                Click here to go back
          </button>
        <div>
        <table class="table">
            <tbody>
              {dataTable.map((value,index)=>{
                return( 
                <tr>
                 <th scope="row">{value.number}</th>
                 <td>*</td>
                 <td>{value.multiplier}</td>
                 <td>=</td>
                 <td>{value.Result}</td>
               </tr>)
              })}
             </tbody>
          </table>
        </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
