import Head from 'next/head'
import Image from 'next/image'
 import styles from '../../styles/Home.module.css'
import Link from "next/link"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Table of 5</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div><h1>Table of 5</h1></div>
        <div>
            <p>5*1 = 5</p>
            <p>5*2 = 10</p>
            <p>5*3 = 15</p>
            <p>5*4 = 20</p>
            <p>5*5 = 25</p>
            <p>5*6 = 30</p>
            <p>5*7 = 35</p>
            <p>5*8 = 40</p>
            <p>5*9 = 45</p>
            <p>5*10 = 50</p>
        </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
